[package]

name = "promise"
version = "0.0.2"
authors = ["Chris Gill"]
description = "promise sync primitive"
repository = "https://github.com/viperscape/rust-promise"
readme = "README.md"
license = "MIT"